/**
 * Data for the interactive demo. Portal strings are copied from the app's real
 * customer dictionary (TrackBack/app/lib/i18n.ts) so the demo shows the actual
 * wording customers see. Everything here is fictional: no real order, email or
 * payment is involved.
 */
import { withFrTypo, type Lang } from '../../config/site';

export type ScenarioKey = 'refund' | 'exchange' | 'credit' | 'cod' | 'withdrawal';
export type ResolutionKey = 'original' | 'credit' | 'exchange' | 'offline';
export type StoreKey = 'apparel' | 'cod' | 'eu';
export type Status = 'PENDING' | 'APPROVED' | 'RECEIVED' | 'REFUNDED' | 'REJECTED';

type L = Record<Lang, string>;

export const BONUS_PCT = 10;
export const NEW_RMA = 'RMA-2026-000142';

// ── Portal (customer side) — real TrackBack wording ──────────────────────────
const portalEn = {
  returnCenter: 'Return Center',
  labelFindOrder: 'Find your order',
  descFindOrder: 'Enter your order number and the email used at checkout.',
  labelCta: 'Find order',
  labelSelectItems: 'Select items to return',
  descSelectItems: "Choose the items you'd like to return.",
  labelReasons: 'Tell us why',
  descReasons: "Help us understand why you're returning each item.",
  labelRefundType: 'How would you like to be refunded?',
  descRefundType: 'Choose the option that works best for you.',
  labelConfirm: 'Review & submit',
  descConfirm: 'One last look before we send this.',
  labelSubmit: 'Submit return request',
  labelPoweredBy: 'Secured by TrackBack',
  stepOf: 'Step {n} of {total}',
  back: 'Back',
  continue: 'Continue',
  optional: 'optional',
  stepFind: 'Order',
  stepItems: 'Items',
  stepReason: 'Reason',
  stepResolution: 'Refund',
  stepConfirm: 'Confirm',
  orderNumber: 'Order number',
  emailAddress: 'Email address',
  searching: 'Searching…',
  withdrawLink: 'Withdraw from contract here',
  fromOrder: 'Order {order} · placed {date}',
  returnBy: 'Return by {date}',
  qty: 'Qty',
  reasonFinalSale: 'Final sale — not returnable',
  selectReason: 'Reason',
  chooseReason: 'Choose a reason…',
  notes: 'Additional details',
  notesPlaceholder: 'Anything else we should know?',
  refundOriginalTitle: 'Refund to original payment',
  refundOriginalDesc: 'Back to your original payment method within 5–10 business days.',
  refundOfflineTitle: 'Mobile money or bank transfer',
  refundOfflineDesc: 'You paid on delivery: tell us where to send your refund.',
  storeCreditTitle: 'Store credit',
  storeCreditDesc: 'Use it on your next order, available as soon as your return is processed.',
  bonusBadge: '+{pct}% bonus',
  bonusLine: 'Get {total} instead of {base}',
  exchangeTitle: 'Exchange for another size or color',
  exchangeDesc: 'We ship the replacement as soon as we receive your return.',
  recommended: 'Recommended',
  chooseReplacement: 'Choose the replacement',
  outOfStock: 'Out of stock',
  payoutMethod: 'Refund method',
  payoutAccountPhone: 'Mobile money number',
  payoutAccountBank: 'IBAN or account number',
  payoutAccountOther: 'Account details',
  payoutName: 'Account holder name',
  payoutCashNote: 'The store will contact you to arrange your cash refund.',
  returnMethodTitle: 'How will you send the items back?',
  methodShip: 'Ship it yourself',
  methodShipDesc: 'Send the parcel with the carrier of your choice.',
  methodLabel: 'Prepaid shipping label',
  methodLabelDesc: 'We email you a shipping label once your return is approved.',
  methodStore: 'Drop off in store',
  methodStoreDesc: 'Bring the items to our store.',
  methodPickup: 'Home pickup',
  methodPickupDesc: 'Our courier collects the parcel from you.',
  subtotal: 'Subtotal',
  bonusCredit: 'Store credit bonus (+{pct}%)',
  estimatedRefund: 'Estimated refund',
  totalCredit: 'Total store credit',
  exchangeValue: 'Exchange value',
  refundMethodLabel: 'Refund',
  returnMethodLabel: 'Return method',
  phoneLabel: 'Phone number (WhatsApp)',
  whatsappOptIn: 'Send me updates about my return on WhatsApp',
  submitting: 'Submitting…',
  agreePolicy: 'By submitting, you agree to our return policy.',
  submittedTitle: 'Your return request is submitted',
  submittedDesc: "We've emailed you a confirmation with the next steps.",
  yourRma: 'Your return number',
  nextSteps: 'Next steps',
  stepReview: 'We review your request, usually within 1 business day.',
  stepShipAfterApproval: 'Once approved, we email you the return address.',
  stepLabel: "Once approved, you'll receive a prepaid label by email.",
  stepStore: 'Bring the items to our store.',
  stepPickup: 'Our courier will contact you to collect the parcel.',
  stepRefund: 'Once received, your refund is issued within 3–5 business days.',
  stepCredit: 'Your store credit is issued as soon as we receive the items.',
  stepExchange: 'Your replacement ships as soon as we receive your return.',
  writeRma: 'Write {rma} on the parcel.',
  trackThisReturn: 'Track this return',
  statusTitle: 'Track your return',
  status_PENDING: 'Under review',
  status_APPROVED: 'Approved — waiting for your parcel',
  status_RECEIVED: 'Received — being processed',
  status_REFUNDED: 'Completed',
  status_REJECTED: 'Declined',
  tlRequested: 'Request received',
  tlApproved: 'Approved',
  tlReceived: 'Items received',
  tlRefunded: 'Refund issued',
  tlRejected: 'Declined',
  refundDone: '{method}: {amount}',
  newReturn: 'Start a new return',
  withdrawTitle: 'Withdraw from your purchase',
  withdrawDesc: 'You can withdraw within 14 days of delivery, without giving any reason.',
  withdrawName: 'Full name',
  withdrawItems: 'Items concerned',
  withdrawComment: 'Comment',
  withdrawConfirm: 'Confirm withdrawal',
  withdrawDoneTitle: 'Your withdrawal is registered',
  withdrawDoneDesc: 'Received on {date}. A confirmation has been sent to {email}.',
  errInvalidEmail: 'Please enter a valid email address.',
  errPayout: 'Please complete your refund details.',
};

export type PortalStrings = typeof portalEn;

const portalFr: PortalStrings = {
  returnCenter: 'Centre de retours',
  labelFindOrder: 'Retrouvez votre commande',
  descFindOrder: "Saisissez votre numéro de commande et l'e-mail utilisé lors de l'achat.",
  labelCta: 'Rechercher',
  labelSelectItems: 'Sélectionnez les articles à retourner',
  descSelectItems: 'Choisissez les articles que vous souhaitez retourner.',
  labelReasons: 'Dites-nous pourquoi',
  descReasons: 'Aidez-nous à comprendre la raison de chaque retour.',
  labelRefundType: 'Comment souhaitez-vous être remboursé ?',
  descRefundType: "Choisissez l'option qui vous convient le mieux.",
  labelConfirm: 'Vérifiez et envoyez',
  descConfirm: "Un dernier coup d'œil avant l'envoi.",
  labelSubmit: 'Envoyer la demande de retour',
  labelPoweredBy: 'Sécurisé par TrackBack',
  stepOf: 'Étape {n} sur {total}',
  back: 'Retour',
  continue: 'Continuer',
  optional: 'facultatif',
  stepFind: 'Commande',
  stepItems: 'Articles',
  stepReason: 'Motif',
  stepResolution: 'Remboursement',
  stepConfirm: 'Validation',
  orderNumber: 'Numéro de commande',
  emailAddress: 'Adresse e-mail',
  searching: 'Recherche…',
  withdrawLink: 'Se rétracter du contrat ici',
  fromOrder: 'Commande {order} · passée le {date}',
  returnBy: 'À retourner avant le {date}',
  qty: 'Qté',
  reasonFinalSale: 'Vente finale : non reprise',
  selectReason: 'Motif',
  chooseReason: 'Choisissez un motif…',
  notes: 'Précisions',
  notesPlaceholder: 'Autre chose à nous signaler ?',
  refundOriginalTitle: 'Remboursement sur votre moyen de paiement',
  refundOriginalDesc: "Sur votre moyen de paiement d'origine sous 5 à 10 jours ouvrés.",
  refundOfflineTitle: 'Mobile money ou virement',
  refundOfflineDesc: 'Vous avez payé à la livraison : indiquez-nous où envoyer votre remboursement.',
  storeCreditTitle: 'Avoir en boutique',
  storeCreditDesc: 'À utiliser sur votre prochaine commande, dès le traitement de votre retour.',
  bonusBadge: '+{pct} % offerts',
  bonusLine: 'Recevez {total} au lieu de {base}',
  exchangeTitle: 'Échanger contre une autre taille ou couleur',
  exchangeDesc: 'Nous expédions le remplacement dès réception de votre retour.',
  recommended: 'Recommandé',
  chooseReplacement: 'Choisissez le remplacement',
  outOfStock: 'Épuisé',
  payoutMethod: 'Mode de remboursement',
  payoutAccountPhone: 'Numéro mobile money',
  payoutAccountBank: 'IBAN ou numéro de compte',
  payoutAccountOther: 'Coordonnées',
  payoutName: 'Nom du titulaire',
  payoutCashNote: 'La boutique vous contactera pour organiser votre remboursement en espèces.',
  returnMethodTitle: 'Comment nous renvoyez-vous les articles ?',
  methodShip: "Je l'expédie moi-même",
  methodShipDesc: 'Envoyez le colis avec le transporteur de votre choix.',
  methodLabel: 'Étiquette prépayée',
  methodLabelDesc: "Nous vous envoyons une étiquette dès l'acceptation du retour.",
  methodStore: 'Dépôt en boutique',
  methodStoreDesc: 'Rapportez les articles en boutique.',
  methodPickup: 'Enlèvement à domicile',
  methodPickupDesc: 'Notre livreur récupère le colis chez vous.',
  subtotal: 'Sous-total',
  bonusCredit: 'Bonus avoir (+{pct} %)',
  estimatedRefund: 'Remboursement estimé',
  totalCredit: "Total de l'avoir",
  exchangeValue: "Valeur de l'échange",
  refundMethodLabel: 'Remboursement',
  returnMethodLabel: 'Mode de retour',
  phoneLabel: 'Numéro de téléphone (WhatsApp)',
  whatsappOptIn: 'Recevoir le suivi de mon retour sur WhatsApp',
  submitting: 'Envoi…',
  agreePolicy: 'En envoyant cette demande, vous acceptez notre politique de retour.',
  submittedTitle: 'Votre demande de retour est envoyée',
  submittedDesc: 'Un e-mail de confirmation avec les prochaines étapes vous a été envoyé.',
  yourRma: 'Votre numéro de retour',
  nextSteps: 'Prochaines étapes',
  stepReview: 'Nous examinons votre demande, en général sous 1 jour ouvré.',
  stepShipAfterApproval: "Après validation, nous vous envoyons l'adresse de retour par e-mail.",
  stepLabel: 'Après validation, vous recevrez une étiquette prépayée par e-mail.',
  stepStore: 'Rapportez les articles en boutique.',
  stepPickup: 'Notre livreur vous contactera pour récupérer le colis.',
  stepRefund: 'Dès réception, votre remboursement est effectué sous 3 à 5 jours ouvrés.',
  stepCredit: 'Votre avoir est émis dès réception des articles.',
  stepExchange: 'Votre article de remplacement part dès réception de votre retour.',
  writeRma: 'Indiquez {rma} sur le colis.',
  trackThisReturn: 'Suivre ce retour',
  statusTitle: 'Suivre votre retour',
  status_PENDING: "En cours d'examen",
  status_APPROVED: 'Accepté : en attente de votre colis',
  status_RECEIVED: 'Reçu : en cours de traitement',
  status_REFUNDED: 'Terminé',
  status_REJECTED: 'Refusé',
  tlRequested: 'Demande reçue',
  tlApproved: 'Acceptée',
  tlReceived: 'Articles reçus',
  tlRefunded: 'Remboursement effectué',
  tlRejected: 'Refusée',
  refundDone: '{method} : {amount}',
  newReturn: 'Faire un nouveau retour',
  withdrawTitle: 'Se rétracter de votre achat',
  withdrawDesc: 'Vous pouvez vous rétracter dans les 14 jours suivant la livraison, sans avoir à vous justifier.',
  withdrawName: 'Nom complet',
  withdrawItems: 'Articles concernés',
  withdrawComment: 'Commentaire',
  withdrawConfirm: 'Confirmer la rétractation',
  withdrawDoneTitle: 'Votre rétractation est enregistrée',
  withdrawDoneDesc: 'Reçue le {date}. Une confirmation a été envoyée à {email}.',
  errInvalidEmail: 'Veuillez saisir une adresse e-mail valide.',
  errPayout: 'Veuillez compléter vos informations de remboursement.',
};

export const PORTAL: Record<Lang, PortalStrings> = { en: portalEn, fr: portalFr };

export const REASONS: { key: string; label: L }[] = [
  { key: 'too_small', label: { en: 'Too small', fr: 'Trop petit' } },
  { key: 'too_large', label: { en: 'Too large', fr: 'Trop grand' } },
  { key: 'not_as_described', label: { en: 'Not as described', fr: 'Différent de la description' } },
  { key: 'damaged', label: { en: 'Damaged or defective', fr: 'Endommagé ou défectueux' } },
  { key: 'changed_mind', label: { en: 'Changed my mind', fr: "Je n'en veux plus" } },
  { key: 'other', label: { en: 'Other', fr: 'Autre' } },
];

/** Same list and order as PAYOUT_METHODS in the app. */
export const PAYOUT_METHODS: { key: string; label: L; kind: 'phone' | 'bank' | 'cash' | 'other'; ref: string }[] = [
  { key: 'wave', label: { en: 'Wave', fr: 'Wave' }, kind: 'phone', ref: 'WAVE' },
  { key: 'orange_money', label: { en: 'Orange Money', fr: 'Orange Money' }, kind: 'phone', ref: 'OM' },
  { key: 'mtn_momo', label: { en: 'MTN MoMo', fr: 'MTN MoMo' }, kind: 'phone', ref: 'MOMO' },
  { key: 'moov_money', label: { en: 'Moov Money', fr: 'Moov Money' }, kind: 'phone', ref: 'MOOV' },
  { key: 'mpesa', label: { en: 'M-Pesa', fr: 'M-Pesa' }, kind: 'phone', ref: 'MPESA' },
  { key: 'airtel_money', label: { en: 'Airtel Money', fr: 'Airtel Money' }, kind: 'phone', ref: 'AIRTEL' },
  { key: 'bank_transfer', label: { en: 'Bank transfer', fr: 'Virement bancaire' }, kind: 'bank', ref: 'VIR' },
  { key: 'cash', label: { en: 'Cash', fr: 'Espèces' }, kind: 'cash', ref: 'CASH' },
  { key: 'other', label: { en: 'Other', fr: 'Autre' }, kind: 'other', ref: 'REF' },
];

export const RETURN_METHODS = ['ship', 'label', 'store', 'pickup'] as const;
export type ReturnMethod = (typeof RETURN_METHODS)[number];

// ── Demo stores (fictional) ──────────────────────────────────────────────────
export type DemoItem = { id: string; title: L; variant: L; price: number; eligible: boolean; color: string; icon: 'shirt' | 'bag' };

export type DemoStore = {
  name: string;
  currency: Record<Lang, string>;
  order: string;
  customer: string;
  email: string;
  phone: string;
  payment: L;
  offline: boolean;
  items: DemoItem[];
  variants?: { id: string; stock: boolean }[];
  exchangeOrder?: string;
  retainedBase: number;
  rows: { rma: string; who: string; order: string; what: L; status: Status }[];
};

export const STORES: Record<StoreKey, DemoStore> = {
  apparel: {
    name: 'Northwind Apparel',
    currency: { en: 'USD', fr: 'EUR' },
    order: '#1089',
    customer: 'Sarah Chen',
    email: 'sarah@example.com',
    phone: '+1 415 555 0142',
    payment: { en: 'Visa •••• 4242', fr: 'Visa •••• 4242' },
    offline: false,
    items: [
      { id: 'shirt', title: { en: 'Everyday Linen Shirt', fr: 'Chemise en lin Everyday' }, variant: { en: 'Sage / M', fr: 'Sauge / M' }, price: 89, eligible: true, color: '#7fa88c', icon: 'shirt' },
      { id: 'tote', title: { en: 'Weekend Tote', fr: 'Cabas Weekend' }, variant: { en: 'Black', fr: 'Noir' }, price: 45, eligible: false, color: '#3a4152', icon: 'bag' },
    ],
    variants: [
      { id: 'S', stock: true },
      { id: 'L', stock: true },
      { id: 'XL', stock: false },
    ],
    exchangeOrder: '#1090',
    retainedBase: 1284,
    rows: [
      { rma: 'RMA-2026-000141', who: 'Marc Dubois', order: '#1086', what: { en: 'Exchange', fr: 'Échange' }, status: 'APPROVED' },
      { rma: 'RMA-2026-000140', who: 'Yuki Tanaka', order: '#1082', what: { en: 'Refund', fr: 'Remboursement' }, status: 'REFUNDED' },
    ],
  },
  cod: {
    name: 'Maison Awa',
    currency: { en: 'XOF', fr: 'XOF' },
    order: '#1094',
    customer: 'Awa Diop',
    email: 'awa@example.com',
    phone: '+221 77 123 45 67',
    payment: { en: 'Cash on delivery', fr: 'Paiement à la livraison' },
    offline: true,
    items: [
      { id: 'dress', title: { en: 'Wax print dress', fr: 'Robe en wax' }, variant: { en: 'Size M', fr: 'Taille M' }, price: 45000, eligible: true, color: '#d9962f', icon: 'shirt' },
      { id: 'sandals', title: { en: 'Leather sandals', fr: 'Sandales en cuir' }, variant: { en: 'Size 38', fr: 'Pointure 38' }, price: 25000, eligible: true, color: '#8e6147', icon: 'bag' },
    ],
    retainedBase: 612000,
    rows: [
      { rma: 'RMA-2026-000139', who: 'Fatou Ndiaye', order: '#1090', what: { en: 'Orange Money', fr: 'Orange Money' }, status: 'RECEIVED' },
      { rma: 'RMA-2026-000138', who: 'Kofi Mensah', order: '#1087', what: { en: 'Store credit', fr: 'Avoir' }, status: 'REFUNDED' },
    ],
  },
  eu: {
    name: 'Atelier Lune',
    currency: { en: 'EUR', fr: 'EUR' },
    order: '#2041',
    customer: 'Léa Martin',
    email: 'lea@example.com',
    phone: '+33 6 12 34 56 78',
    payment: { en: 'Visa •••• 1881', fr: 'Visa •••• 1881' },
    offline: false,
    items: [
      { id: 'shirt2', title: { en: 'Linen shirt', fr: 'Chemise en lin' }, variant: { en: 'Blue / S', fr: 'Bleu / S' }, price: 79, eligible: true, color: '#6f8fb8', icon: 'shirt' },
      { id: 'scarf', title: { en: 'Wool scarf', fr: 'Écharpe en laine' }, variant: { en: 'Grey', fr: 'Gris' }, price: 45, eligible: true, color: '#8f96a3', icon: 'bag' },
    ],
    retainedBase: 842,
    rows: [
      { rma: 'RMA-2026-000131', who: 'Hugo Bernard', order: '#2033', what: { en: 'Refund', fr: 'Remboursement' }, status: 'APPROVED' },
      { rma: 'RMA-2026-000130', who: 'Chloé Petit', order: '#2029', what: { en: 'Withdrawal', fr: 'Rétractation' }, status: 'REFUNDED' },
    ],
  },
};

export type Scenario = {
  store: StoreKey;
  flow: 'return' | 'withdrawal';
  resolution: ResolutionKey | null;
  reason: string;
  note: L;
  selected: string[];
};

export const SCENARIOS: Record<ScenarioKey, Scenario> = {
  refund: { store: 'apparel', flow: 'return', resolution: 'original', reason: 'too_small', note: { en: 'The sleeves are a bit short.', fr: 'Les manches sont un peu courtes.' }, selected: ['shirt'] },
  exchange: { store: 'apparel', flow: 'return', resolution: 'exchange', reason: 'too_small', note: { en: 'I need one size up.', fr: "J'ai besoin d'une taille au-dessus." }, selected: ['shirt'] },
  credit: { store: 'apparel', flow: 'return', resolution: 'credit', reason: 'changed_mind', note: { en: '', fr: '' }, selected: ['shirt'] },
  cod: { store: 'cod', flow: 'return', resolution: 'offline', reason: 'not_as_described', note: { en: 'The color is darker than on the photos.', fr: 'La couleur est plus foncée que sur les photos.' }, selected: ['dress'] },
  withdrawal: { store: 'eu', flow: 'withdrawal', resolution: null, reason: '', note: { en: '', fr: '' }, selected: ['shirt2', 'scarf'] },
};

export const SCENARIO_ORDER: ScenarioKey[] = ['refund', 'exchange', 'credit', 'cod', 'withdrawal'];

// ── Page chrome + merchant side ──────────────────────────────────────────────
const demoEn = {
  scenarioLabel: 'Pick a scenario',
  scenarios: {
    refund: { label: 'Refund', hint: 'Card order refunded in Shopify' },
    exchange: { label: 'Exchange', hint: 'Swap sizes, keep the sale' },
    credit: { label: 'Store credit', hint: '+10% bonus instead of a refund' },
    cod: { label: 'Cash on delivery', hint: 'Mobile money payout' },
    withdrawal: { label: 'EU withdrawal', hint: 'Two-step legal flow' },
  } as Record<ScenarioKey, { label: string; hint: string }>,
  restart: 'Restart',
  tabs: { customer: 'Customer portal', merchant: 'Merchant admin' },
  customerSide: 'What your customer sees',
  merchantSide: 'What your team sees',
  portalLang: 'Portal language',
  notice: 'Demo only: no real order, email or payment is involved.',
  admin: {
    crumb: 'Shopify admin › Apps › TrackBack',
    returns: 'Returns',
    pending: 'Pending',
    retained: 'Retained revenue',
    newBadge: 'New',
    emptyTitle: 'Waiting for a request…',
    emptyReturn: 'Submit the return in the portal: it lands here, ready to review.',
    emptyWithdrawal: 'Confirm the withdrawal in the portal: it lands here with its refund deadline.',
    activity: 'Activity',
    customer: 'Customer',
    order: 'Order',
    items: 'Items',
    reason: 'Reason',
    resolution: 'Resolution',
    value: 'Value',
    payout: 'Pay out to',
    returnMethod: 'Return method',
    deadline: 'Refund due by',
    whatsapp: 'WhatsApp updates',
    enabled: 'On',
    reference: 'Payment reference',
    withdrawalTag: 'EU withdrawal',
    statuses: { PENDING: 'Pending', APPROVED: 'Approved', RECEIVED: 'Received', REFUNDED: 'Completed', REJECTED: 'Rejected' } as Record<Status, string>,
    actions: {
      approve: 'Approve',
      reject: 'Reject',
      message: 'Message',
      receive: 'Mark as received',
      refund: 'Issue refund',
      credit: 'Issue store credit',
      exchange: 'Create exchange order',
      payout: 'Record payout',
      instructions: 'Send return instructions',
    },
    resolutions: {
      original: 'Refund to original payment',
      credit: 'Store credit (+{pct}%)',
      exchange: 'Exchange for size {variant}',
      offline: '{method} payout',
      withdrawal: 'Refund to original payment',
    },
    events: {
      verified: 'Order {order} verified in Shopify',
      created: '{rma} created · {count} item(s)',
      emailSubmitted: 'Confirmation email sent to {email} ({lang})',
      whatsapp: 'WhatsApp update sent to {phone}',
      approved: 'Return approved by you',
      instructions: 'Return instructions emailed · {method}',
      rejected: 'Return rejected · customer notified by email',
      received: 'Items received · restocked in Shopify',
      refunded: 'Refund of {amount} created in Shopify · {payment}',
      credited: 'Store credit of {amount} issued in Shopify (+{pct}% bonus)',
      exchanged: 'Exchange order {order} created in Shopify · size {variant}',
      paidOut: '{method} payout of {amount} recorded in Shopify · ref {ref}',
      emailDone: 'Email sent to the customer · “{subject}”',
      message: 'Live chat message sent to {name}',
      withdrawalReceived: 'Withdrawal statement received · {datetime}',
      withdrawalAck: 'Acknowledgment emailed to {email} (durable medium)',
      withdrawalCreated: '{rma} created · refund due by {date}',
    },
    subjects: {
      refunded: 'Your refund has been issued',
      credited: 'Your store credit is ready',
      exchanged: 'Your replacement is on its way',
      paidOut: 'Your refund has been sent',
    },
  },
  toasts: {
    submitted: 'New return received on the merchant side',
    email: 'Email sent to {email}',
    whatsapp: 'WhatsApp update sent',
    message: 'Message sent via live chat (Pro)',
  },
  seeMerchant: 'Now handle it as the merchant',
  done: {
    title: 'Return handled, end to end.',
    text: 'Request, approval and {resolution}: all synced with Shopify, in under a minute.',
    resolutionWords: {
      original: 'refund',
      credit: 'store credit',
      exchange: 'exchange order',
      offline: 'mobile money payout',
      withdrawal: 'refund',
    } as Record<ResolutionKey | 'withdrawal', string>,
    rejectedTitle: 'Return declined.',
    rejectedText: 'The customer was notified by email, and their tracking page shows the decision.',
    cta: 'Install free on Shopify',
    again: 'Try another scenario',
  },
};

export type DemoStrings = typeof demoEn;

const demoFr: DemoStrings = {
  scenarioLabel: 'Choisissez un scénario',
  scenarios: {
    refund: { label: 'Remboursement', hint: 'Commande par carte remboursée dans Shopify' },
    exchange: { label: 'Échange', hint: 'Changer de taille, garder la vente' },
    credit: { label: 'Avoir', hint: '+10 % de bonus au lieu du remboursement' },
    cod: { label: 'Paiement à la livraison', hint: 'Remboursement par mobile money' },
    withdrawal: { label: 'Rétractation UE', hint: 'Parcours légal en deux étapes' },
  },
  restart: 'Recommencer',
  tabs: { customer: 'Portail client', merchant: 'Admin marchand' },
  customerSide: 'Ce que voit votre client',
  merchantSide: 'Ce que voit votre équipe',
  portalLang: 'Langue du portail',
  notice: "Démo uniquement : aucune vraie commande, aucun e-mail ni paiement n'est impliqué.",
  admin: {
    crumb: 'Admin Shopify › Applications › TrackBack',
    returns: 'Retours',
    pending: 'En attente',
    retained: 'CA conservé',
    newBadge: 'Nouveau',
    emptyTitle: "En attente d'une demande…",
    emptyReturn: 'Envoyez le retour dans le portail : il arrive ici, prêt à être traité.',
    emptyWithdrawal: 'Confirmez la rétractation dans le portail : elle arrive ici avec sa date limite de remboursement.',
    activity: 'Activité',
    customer: 'Client',
    order: 'Commande',
    items: 'Articles',
    reason: 'Motif',
    resolution: 'Résolution',
    value: 'Montant',
    payout: 'Verser à',
    returnMethod: 'Mode de retour',
    deadline: 'Remboursement avant le',
    whatsapp: 'Suivi WhatsApp',
    enabled: 'Activé',
    reference: 'Référence du paiement',
    withdrawalTag: 'Rétractation UE',
    statuses: { PENDING: 'En attente', APPROVED: 'Accepté', RECEIVED: 'Reçu', REFUNDED: 'Terminé', REJECTED: 'Refusé' },
    actions: {
      approve: 'Accepter',
      reject: 'Refuser',
      message: 'Message',
      receive: 'Marquer comme reçu',
      refund: 'Rembourser',
      credit: "Émettre l'avoir",
      exchange: "Créer la commande d'échange",
      payout: 'Enregistrer le versement',
      instructions: 'Envoyer les instructions de retour',
    },
    resolutions: {
      original: 'Remboursement sur le moyen de paiement',
      credit: 'Avoir (+{pct} %)',
      exchange: 'Échange en taille {variant}',
      offline: 'Versement {method}',
      withdrawal: 'Remboursement sur le moyen de paiement',
    },
    events: {
      verified: 'Commande {order} vérifiée dans Shopify',
      created: '{rma} créé · {count} article(s)',
      emailSubmitted: 'E-mail de confirmation envoyé à {email} ({lang})',
      whatsapp: 'Suivi WhatsApp envoyé au {phone}',
      approved: 'Retour accepté par vous',
      instructions: 'Instructions de retour envoyées · {method}',
      rejected: 'Retour refusé · client prévenu par e-mail',
      received: 'Articles reçus · remis en stock dans Shopify',
      refunded: 'Remboursement de {amount} créé dans Shopify · {payment}',
      credited: 'Avoir de {amount} émis dans Shopify (+{pct} % de bonus)',
      exchanged: "Commande d'échange {order} créée dans Shopify · taille {variant}",
      paidOut: 'Versement {method} de {amount} enregistré dans Shopify · réf. {ref}',
      emailDone: 'E-mail envoyé au client · « {subject} »',
      message: 'Message envoyé à {name} par le chat',
      withdrawalReceived: 'Déclaration de rétractation reçue · {datetime}',
      withdrawalAck: 'Accusé de réception envoyé à {email} (support durable)',
      withdrawalCreated: '{rma} créé · remboursement avant le {date}',
    },
    subjects: {
      refunded: 'Votre remboursement a été effectué',
      credited: 'Votre avoir est disponible',
      exchanged: 'Votre article de remplacement est en route',
      paidOut: 'Votre remboursement a été envoyé',
    },
  },
  toasts: {
    submitted: 'Nouveau retour reçu côté marchand',
    email: 'E-mail envoyé à {email}',
    whatsapp: 'Suivi WhatsApp envoyé',
    message: 'Message envoyé par le chat (Pro)',
  },
  seeMerchant: 'Traitez-le maintenant côté marchand',
  done: {
    title: 'Retour traité de bout en bout.',
    text: 'Demande, validation et {resolution} : tout est synchronisé avec Shopify, en moins d’une minute.',
    resolutionWords: {
      original: 'remboursement',
      credit: 'avoir',
      exchange: "commande d'échange",
      offline: 'versement mobile money',
      withdrawal: 'remboursement',
    },
    rejectedTitle: 'Retour refusé.',
    rejectedText: 'Le client a été prévenu par e-mail, et sa page de suivi affiche la décision.',
    cta: 'Installer gratuitement sur Shopify',
    again: 'Essayer un autre scénario',
  },
};

export const DEMO: Record<Lang, DemoStrings> = { en: demoEn, fr: withFrTypo(demoFr) };
